import { getCommitDiff } from '../git/git-service';
import { streamAiChat, type ResolvedAi } from './chat';

/**
 * Commit messages are generated by the user's configured AI provider (the local `claude` CLI by
 * default, or the Anthropic / OpenAI APIs). We stream the reply and collect it into a string.
 */
const SYSTEM_PROMPT = 'You write clear, conventional git commit messages.';

const INSTRUCTION = [
  'Write a git commit message for the staged/working changes in the diff above.',
  'Rules:',
  '- Use the imperative mood ("Add", "Fix", "Refactor"), not past tense.',
  '- First line: a concise summary under 72 characters. No trailing period.',
  '- If the change is non-trivial, add a blank line then 1-3 short bullet points ("- …").',
  '- Describe what changed and why, not the mechanics of the diff.',
  '- Do NOT wrap the message in quotes, backticks, or markdown code fences.',
  '- Output ONLY the commit message — no preamble, no explanation.',
].join('\n');

/** Strip any stray code fences / surrounding quotes a model might add, then trim. */
function cleanMessage(raw: string): string {
  let m = raw.trim();
  if (m.startsWith('```')) m = m.replace(/^```[^\n]*\n?/, '').replace(/\n?```$/, '').trim();
  if (m.length > 1 && m.startsWith('"') && m.endsWith('"')) m = m.slice(1, -1).trim();
  return m;
}

/**
 * Generate a commit message describing the repo's pending changes. Throws when there's nothing to
 * describe or the provider fails.
 */
export async function generateCommitMessage(cfg: ResolvedAi, rootPath: string): Promise<string> {
  const diff = await getCommitDiff(rootPath);
  if (!diff.trim()) throw new Error('No changes to describe.');

  const text = await new Promise<string>((resolve, reject) => {
    let out = '';
    streamAiChat(
      cfg,
      { system: SYSTEM_PROMPT, history: [], question: INSTRUCTION, context: diff, maxTokens: 512 },
      (delta) => {
        out += delta;
      },
      (error) => (error ? reject(new Error(error)) : resolve(out)),
    );
  });

  const message = cleanMessage(text);
  if (!message) throw new Error('The AI returned an empty message.');
  return message;
}
